import Lean

/-!
# Small utilities

`Expr` traversal, name sanitation, and a few predicates needed across several stages.
-/

namespace Hammer

open Lean Meta

/-- Constants for the logical connectives and quantifiers. Feature extraction ignores
them; otherwise every lemma looks relevant to every goal. -/
def logicalSymbols : Std.HashSet Name :=
  Std.HashSet.ofList
    [``Eq, ``Ne, ``Iff, ``And, ``Or, ``Not, ``Exists, ``True, ``False,
     ``HEq, ``ite, ``dite, ``Decidable, ``DecidableEq,
     ``OfNat.ofNat, ``instOfNatNat, ``Membership.mem]

/-- Namespaces skipped wholesale during premise collection. -/
def blacklistedNamespaces : Array Name :=
  #[`Lean, `Std.Internal, `Qq, `Aesop, `Mathlib.Tactic, `Mathlib.Meta,
    `Tactic, `Simp, `Elab, `Parser, `IO, `EIO, `ST, `Hammer]

/-- Whether a name lives in a blacklisted namespace. -/
def isBlacklisted (n : Name) : Bool :=
  blacklistedNamespaces.any fun ns => ns.isPrefixOf n

/-- Auxiliary definitions generated by the compiler or elaborator. They are invisible to
users and make poor premises. -/
def isNoise (n : Name) : Bool := Id.run do
  if n.isInternal || n.hasMacroScopes then return true
  let s := n.toString
  for bad in ["_proof_", "_eq_", "_unfold", "match_", "eq_def", "proof_",
              "._", "sizeOf_spec", "noConfusion", "casesOn", "recOn", "brecOn",
              "below", "ibelow", "binductionOn", "ndrec", "rec_", "injEq",
              "toCtorIdx", "ofNat_toCtorIdx"] do
    if (s.splitOn bad).length > 1 then return true
  return false

/-- Every constant name occurring in `e`. -/
def constantsIn (e : Expr) : Std.HashSet Name :=
  (e.foldConsts ∅ fun n acc => acc.insert n)

/-- Whether an expression is `Prop` when read as a type. -/
def isPropType (e : Expr) : MetaM Bool := do
  return (← whnf (← inferType e)).isProp

/-- Turn a Lean name into a legal SMT-LIB symbol. -/
def sanitize (n : Name) : String :=
  let s := n.toString
  let s := s.foldl (init := "") fun acc c =>
    if c.isAlphanum || c == '_' then acc.push c
    else if c == '.' then acc.push '_'
    else acc ++ "u" ++ toString c.toNat
  if s.isEmpty then "sym"
  else if s.front.isDigit then "s" ++ s
  else s

end Hammer
